
export { default as Home } from './home/home'
export { default as CreateForm } from './createform/createform'
export { default as ListView } from './listview/listview'
export { default as DetailedView } from './detailview/detailview'
export { default as Settings } from './settings/settings'
export { default as Announcements } from './announcements/announcements'
export { default as KnowledgeArticles } from './knowledgearticles/knowledgearticles'
export { default as QandA } from './qa/qa'
export { default as Calendar } from './calendar/calendar'
export { default as PointsOfContacts } from './poc/pointsofcontacts'
